import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import LightboxGallery from '@/components/LightboxGallery';

const inter = Inter({ subsets: ['latin'] });

const images = [
  {
    src: 'https://i.pinimg.com/550x/e1/20/e2/e120e29d79675d22a1b62a5c88e46856.jpg',
    alt: 'After Rain (Jeshu John - designerspics.com)',
  },
  {
    src: 'https://thumbs.dreamstime.com/b/american-duplex-house-two-families-green-exterior-paint-76170460.jpg',
    alt: 'Boats (Jeshu John - designerspics.com)',
  },

  {
    src: 'https://thumbs.dreamstime.com/b/duplex-11389954.jpg',
    alt: 'another alt',
  },
  {
    src: 'https://thumbs.dreamstime.com/b/modern-large-house-8122926.jpg',
    alt: 'another alt',
  },
  {
    src: 'https://thumbs.dreamstime.com/b/new-modern-bungalow-front-view-one-floor-family-house-asia-style-design-149517329.jpg',
    alt: 'After Rain (Jeshu John - designerspics.com)',
  },
  {
    src: 'https://thumbs.dreamstime.com/b/stone-brick-duplex-776712.jpg',
    alt: 'Boats (Jeshu John - designerspics.com)',
  },

  {
    src: 'https://thumbs.dreamstime.com/b/living-room-orange-sofa-8815301.jpg',
    alt: 'another alt',
  },
  {
    src: 'https://thumbs.dreamstime.com/b/two-houses-15993105.jpg',
    alt: 'another alt',
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <LightboxGallery images={images} />
      </main>
    </>
  );
}
